project:
  type: website
  resources: static/*
  output-dir: ../_site

website:
  title: "ARC-travellingo"
  image: "android-chrome-512x512.png"
  favicon: "favicon.ico"
  open-graph: true
  twitter-card: true
  repo-url: https://github.com/UCL-ARC-Workshops/202405-arcgit-workshop
  page-navigation: true
  search: true
  back-to-top-navigation: true
  page-footer:
    center:
      - text: "License"
        href: license.qmd
  navbar:
    title: "is travelling"
    background: dark
    logo: UCL-ARC.png
    logo-alt: "ARC logo."
    collapse-below: lg
    right:
      - href: cities.qmd
        text: Cities
      - href: travellers.qmd
        text: Travellers

format:
  html:
    toc: false
    theme: sandstone
    css: styles.css
    code-copy: true
    code-overflow: wrap
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
